---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
      - recipe[learn_chef_apache2::groups]
      - recipe[learn_chef_apache2::users]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
